name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes files from 'fold' directory
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.SUKTRIAL_TOKEN }}
      with:
        source_file: 'fold/' ; 'bro/' # Specify the directory you want to copy
        destination_repo: 'Suk-Trials/test'
        user_email: 'eng21ct0039@dsu.edu.in'
        user_name: 's-sukriti'
        commit_message: 'A message for the commit'
